---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: get the list of users
    local_action: shell ls -al /elk_data/ansible/keys/ |awk '{print $9}'| cut -f1 -d '.'|grep -v '^$'
    register: users

  - name: add lines to sudoers file
    shell: echo '{{ item }}   ALL=(ALL)       NOPASSWD{{':'}} ALL' >> /elk_data/test
    become: yes
    with_items: "{{ users.stdout_lines }}"
