---
- hosts: slaves
  gather_facts: no

  tasks:
  - name: get the list of users
    local_action: shell ls -al /elk_data/ansible/keys/ |awk '{print $9}'| cut -f1 -d '.'|grep -v '^$'
    register: users
  
  - name: Make sure we have a 'dbadmin' group
    group:
      name: dbadmin
      state: present
    become: yes
    become_method: "sudo"

  - name: Ensure /etc/sudoers.d directory is present
    file: path=/etc/sudoers.d state=directory

  - name: Ensure /etc/sudoers.d is scanned by sudo
    action: lineinfile dest=/etc/sudoers regexp="#includedir\s+/etc/sudoers.d" line="#includedir /etc/sudoers.d"

  - name: Add dbadmin user to the sudoers
    action: 'lineinfile dest=/etc/sudoers.d/dbadmin state=present create=yes regexp="dbadmin .*" line="%dbadmin ALL=(ALL) NOPASSWD: ALL"'
    tags: dbadmin

  - name: Ensure /etc/sudoers.d/dbadmin file has correct permissions
    action: file path=/etc/sudoers.d/dbadmin mode=0440 state=file owner=root group=root
    tags: dbadmin
 
  - name: create user
    user: 
      name: "{{ item }}"
      createhome: yes
      groups: dbadmin
      state:  present
    with_items: "{{ users.stdout_lines }}"
    become: yes
    become_method: "sudo"

  - name: create .ssh directory
    file: state=directory path=~/.ssh
    become: yes
    become_user: "{{ item }}"
    with_items: "{{ users.stdout_lines }}"


  - name: copy ssh key from ACS
    copy: src="/elk_data/ansible/keys/{{ item }}.pub" dest=~/.ssh/authorized_keys mode=0600
    become: yes
    become_user: "{{ item }}" 
    with_items: "{{ users.stdout_lines }}"
